// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the MachineForceDeleteResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MachineForceDeleteResponse{}

// MachineForceDeleteResponse Resources affected by a forced Machine deletion in NICo Core
type MachineForceDeleteResponse struct {
	// Whether Core completed every deletion step
	AllDone bool `json:"allDone"`
	// ID of the managed host Machine affected by the deletion
	ManagedHostMachineId string `json:"managedHostMachineId"`
	// ID of the managed host Machine interface affected by the deletion
	ManagedHostMachineInterfaceId string `json:"managedHostMachineInterfaceId"`
	// ID of the attached Instance deleted with the Machine
	InstanceId string `json:"instanceId"`
	// BMC IP address of the managed host
	ManagedHostBmcIp string `json:"managedHostBmcIp"`
	// BMC IP address of the first attached DPU
	DpuBmcIp string `json:"dpuBmcIp"`
	// Number of interfaces unregistered from UFM
	UfmUnregistrations uint32 `json:"ufmUnregistrations"`
	// Whether UFM unregistration remains in progress
	UfmUnregistrationPending bool `json:"ufmUnregistrationPending"`
	// Machine lockdown state before the deletion attempted to unlock it
	InitialLockdownState string `json:"initialLockdownState"`
	// Whether the Machine was unlocked during deletion
	MachineUnlocked bool `json:"machineUnlocked"`
	// Whether host interfaces were deleted
	HostInterfacesDeleted bool `json:"hostInterfacesDeleted"`
	// Whether DPU interfaces were deleted
	DpuInterfacesDeleted bool `json:"dpuInterfacesDeleted"`
	// Whether Core found an associated host BMC interface
	HostBmcInterfaceAssociated bool `json:"hostBmcInterfaceAssociated"`
	// Whether Core found an associated DPU BMC interface
	DpuBmcInterfaceAssociated bool `json:"dpuBmcInterfaceAssociated"`
	// Whether the associated host BMC interface was deleted
	HostBmcInterfaceDeleted bool `json:"hostBmcInterfaceDeleted"`
	// Whether the associated DPU BMC interface was deleted
	DpuBmcInterfaceDeleted bool `json:"dpuBmcInterfaceDeleted"`
	// IDs of DPU Machines affected by the deletion
	DpuMachineIds []string `json:"dpuMachineIds"`
	// IDs of DPU Machine interfaces affected by the deletion
	DpuMachineInterfaceIds []string `json:"dpuMachineInterfaceIds"`
}

type _MachineForceDeleteResponse MachineForceDeleteResponse

// NewMachineForceDeleteResponse instantiates a new MachineForceDeleteResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMachineForceDeleteResponse(allDone bool, managedHostMachineId string, managedHostMachineInterfaceId string, instanceId string, managedHostBmcIp string, dpuBmcIp string, ufmUnregistrations uint32, ufmUnregistrationPending bool, initialLockdownState string, machineUnlocked bool, hostInterfacesDeleted bool, dpuInterfacesDeleted bool, hostBmcInterfaceAssociated bool, dpuBmcInterfaceAssociated bool, hostBmcInterfaceDeleted bool, dpuBmcInterfaceDeleted bool, dpuMachineIds []string, dpuMachineInterfaceIds []string) *MachineForceDeleteResponse {
	this := MachineForceDeleteResponse{}
	this.AllDone = allDone
	this.ManagedHostMachineId = managedHostMachineId
	this.ManagedHostMachineInterfaceId = managedHostMachineInterfaceId
	this.InstanceId = instanceId
	this.ManagedHostBmcIp = managedHostBmcIp
	this.DpuBmcIp = dpuBmcIp
	this.UfmUnregistrations = ufmUnregistrations
	this.UfmUnregistrationPending = ufmUnregistrationPending
	this.InitialLockdownState = initialLockdownState
	this.MachineUnlocked = machineUnlocked
	this.HostInterfacesDeleted = hostInterfacesDeleted
	this.DpuInterfacesDeleted = dpuInterfacesDeleted
	this.HostBmcInterfaceAssociated = hostBmcInterfaceAssociated
	this.DpuBmcInterfaceAssociated = dpuBmcInterfaceAssociated
	this.HostBmcInterfaceDeleted = hostBmcInterfaceDeleted
	this.DpuBmcInterfaceDeleted = dpuBmcInterfaceDeleted
	this.DpuMachineIds = dpuMachineIds
	this.DpuMachineInterfaceIds = dpuMachineInterfaceIds
	return &this
}

// NewMachineForceDeleteResponseWithDefaults instantiates a new MachineForceDeleteResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMachineForceDeleteResponseWithDefaults() *MachineForceDeleteResponse {
	this := MachineForceDeleteResponse{}
	return &this
}

// GetAllDone returns the AllDone field value
func (o *MachineForceDeleteResponse) GetAllDone() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AllDone
}

// GetAllDoneOk returns a tuple with the AllDone field value
// and a boolean to check if the value has been set.
func (o *MachineForceDeleteResponse) GetAllDoneOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AllDone, true
}

// SetAllDone sets field value
func (o *MachineForceDeleteResponse) SetAllDone(v bool) {
	o.AllDone = v
}

// GetManagedHostMachineId returns the ManagedHostMachineId field value
func (o *MachineForceDeleteResponse) GetManagedHostMachineId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ManagedHostMachineId
}

// GetManagedHostMachineIdOk returns a tuple with the ManagedHostMachineId field value
// and a boolean to check if the value has been set.
func (o *MachineForceDeleteResponse) GetManagedHostMachineIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ManagedHostMachineId, true
}

// SetManagedHostMachineId sets field value
func (o *MachineForceDeleteResponse) SetManagedHostMachineId(v string) {
	o.ManagedHostMachineId = v
}

// GetManagedHostMachineInterfaceId returns the ManagedHostMachineInterfaceId field value
func (o *MachineForceDeleteResponse) GetManagedHostMachineInterfaceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ManagedHostMachineInterfaceId
}

// GetManagedHostMachineInterfaceIdOk returns a tuple with the ManagedHostMachineInterfaceId field value
// and a boolean to check if the value has been set.
func (o *MachineForceDeleteResponse) GetManagedHostMachineInterfaceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ManagedHostMachineInterfaceId, true
}

// SetManagedHostMachineInterfaceId sets field value
func (o *MachineForceDeleteResponse) SetManagedHostMachineInterfaceId(v string) {
	o.ManagedHostMachineInterfaceId = v
}

// GetInstanceId returns the InstanceId field value
func (o *MachineForceDeleteResponse) GetInstanceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InstanceId
}

// GetInstanceIdOk returns a tuple with the InstanceId field value
// and a boolean to check if the value has been set.
func (o *MachineForceDeleteResponse) GetInstanceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstanceId, true
}

// SetInstanceId sets field value
func (o *MachineForceDeleteResponse) SetInstanceId(v string) {
	o.InstanceId = v
}

// GetManagedHostBmcIp returns the ManagedHostBmcIp field value
func (o *MachineForceDeleteResponse) GetManagedHostBmcIp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ManagedHostBmcIp
}

// GetManagedHostBmcIpOk returns a tuple with the ManagedHostBmcIp field value
// and a boolean to check if the value has been set.
func (o *MachineForceDeleteResponse) GetManagedHostBmcIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ManagedHostBmcIp, true
}

// SetManagedHostBmcIp sets field value
func (o *MachineForceDeleteResponse) SetManagedHostBmcIp(v string) {
	o.ManagedHostBmcIp = v
}

// GetDpuBmcIp returns the DpuBmcIp field value
func (o *MachineForceDeleteResponse) GetDpuBmcIp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DpuBmcIp
}

// GetDpuBmcIpOk returns a tuple with the DpuBmcIp field value
// and a boolean to check if the value has been set.
func (o *MachineForceDeleteResponse) GetDpuBmcIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DpuBmcIp, true
}

// SetDpuBmcIp sets field value
func (o *MachineForceDeleteResponse) SetDpuBmcIp(v string) {
	o.DpuBmcIp = v
}

// GetUfmUnregistrations returns the UfmUnregistrations field value
func (o *MachineForceDeleteResponse) GetUfmUnregistrations() uint32 {
	if o == nil {
		var ret uint32
		return ret
	}

	return o.UfmUnregistrations
}

// GetUfmUnregistrationsOk returns a tuple with the UfmUnregistrations field value
// and a boolean to check if the value has been set.
func (o *MachineForceDeleteResponse) GetUfmUnregistrationsOk() (*uint32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UfmUnregistrations, true
}

// SetUfmUnregistrations sets field value
func (o *MachineForceDeleteResponse) SetUfmUnregistrations(v uint32) {
	o.UfmUnregistrations = v
}

// GetUfmUnregistrationPending returns the UfmUnregistrationPending field value
func (o *MachineForceDeleteResponse) GetUfmUnregistrationPending() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.UfmUnregistrationPending
}

// GetUfmUnregistrationPendingOk returns a tuple with the UfmUnregistrationPending field value
// and a boolean to check if the value has been set.
func (o *MachineForceDeleteResponse) GetUfmUnregistrationPendingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UfmUnregistrationPending, true
}

// SetUfmUnregistrationPending sets field value
func (o *MachineForceDeleteResponse) SetUfmUnregistrationPending(v bool) {
	o.UfmUnregistrationPending = v
}

// GetInitialLockdownState returns the InitialLockdownState field value
func (o *MachineForceDeleteResponse) GetInitialLockdownState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InitialLockdownState
}

// GetInitialLockdownStateOk returns a tuple with the InitialLockdownState field value
// and a boolean to check if the value has been set.
func (o *MachineForceDeleteResponse) GetInitialLockdownStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InitialLockdownState, true
}

// SetInitialLockdownState sets field value
func (o *MachineForceDeleteResponse) SetInitialLockdownState(v string) {
	o.InitialLockdownState = v
}

// GetMachineUnlocked returns the MachineUnlocked field value
func (o *MachineForceDeleteResponse) GetMachineUnlocked() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.MachineUnlocked
}

// GetMachineUnlockedOk returns a tuple with the MachineUnlocked field value
// and a boolean to check if the value has been set.
func (o *MachineForceDeleteResponse) GetMachineUnlockedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MachineUnlocked, true
}

// SetMachineUnlocked sets field value
func (o *MachineForceDeleteResponse) SetMachineUnlocked(v bool) {
	o.MachineUnlocked = v
}

// GetHostInterfacesDeleted returns the HostInterfacesDeleted field value
func (o *MachineForceDeleteResponse) GetHostInterfacesDeleted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HostInterfacesDeleted
}

// GetHostInterfacesDeletedOk returns a tuple with the HostInterfacesDeleted field value
// and a boolean to check if the value has been set.
func (o *MachineForceDeleteResponse) GetHostInterfacesDeletedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HostInterfacesDeleted, true
}

// SetHostInterfacesDeleted sets field value
func (o *MachineForceDeleteResponse) SetHostInterfacesDeleted(v bool) {
	o.HostInterfacesDeleted = v
}

// GetDpuInterfacesDeleted returns the DpuInterfacesDeleted field value
func (o *MachineForceDeleteResponse) GetDpuInterfacesDeleted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.DpuInterfacesDeleted
}

// GetDpuInterfacesDeletedOk returns a tuple with the DpuInterfacesDeleted field value
// and a boolean to check if the value has been set.
func (o *MachineForceDeleteResponse) GetDpuInterfacesDeletedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DpuInterfacesDeleted, true
}

// SetDpuInterfacesDeleted sets field value
func (o *MachineForceDeleteResponse) SetDpuInterfacesDeleted(v bool) {
	o.DpuInterfacesDeleted = v
}

// GetHostBmcInterfaceAssociated returns the HostBmcInterfaceAssociated field value
func (o *MachineForceDeleteResponse) GetHostBmcInterfaceAssociated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HostBmcInterfaceAssociated
}

// GetHostBmcInterfaceAssociatedOk returns a tuple with the HostBmcInterfaceAssociated field value
// and a boolean to check if the value has been set.
func (o *MachineForceDeleteResponse) GetHostBmcInterfaceAssociatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HostBmcInterfaceAssociated, true
}

// SetHostBmcInterfaceAssociated sets field value
func (o *MachineForceDeleteResponse) SetHostBmcInterfaceAssociated(v bool) {
	o.HostBmcInterfaceAssociated = v
}

// GetDpuBmcInterfaceAssociated returns the DpuBmcInterfaceAssociated field value
func (o *MachineForceDeleteResponse) GetDpuBmcInterfaceAssociated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.DpuBmcInterfaceAssociated
}

// GetDpuBmcInterfaceAssociatedOk returns a tuple with the DpuBmcInterfaceAssociated field value
// and a boolean to check if the value has been set.
func (o *MachineForceDeleteResponse) GetDpuBmcInterfaceAssociatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DpuBmcInterfaceAssociated, true
}

// SetDpuBmcInterfaceAssociated sets field value
func (o *MachineForceDeleteResponse) SetDpuBmcInterfaceAssociated(v bool) {
	o.DpuBmcInterfaceAssociated = v
}

// GetHostBmcInterfaceDeleted returns the HostBmcInterfaceDeleted field value
func (o *MachineForceDeleteResponse) GetHostBmcInterfaceDeleted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HostBmcInterfaceDeleted
}

// GetHostBmcInterfaceDeletedOk returns a tuple with the HostBmcInterfaceDeleted field value
// and a boolean to check if the value has been set.
func (o *MachineForceDeleteResponse) GetHostBmcInterfaceDeletedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HostBmcInterfaceDeleted, true
}

// SetHostBmcInterfaceDeleted sets field value
func (o *MachineForceDeleteResponse) SetHostBmcInterfaceDeleted(v bool) {
	o.HostBmcInterfaceDeleted = v
}

// GetDpuBmcInterfaceDeleted returns the DpuBmcInterfaceDeleted field value
func (o *MachineForceDeleteResponse) GetDpuBmcInterfaceDeleted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.DpuBmcInterfaceDeleted
}

// GetDpuBmcInterfaceDeletedOk returns a tuple with the DpuBmcInterfaceDeleted field value
// and a boolean to check if the value has been set.
func (o *MachineForceDeleteResponse) GetDpuBmcInterfaceDeletedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DpuBmcInterfaceDeleted, true
}

// SetDpuBmcInterfaceDeleted sets field value
func (o *MachineForceDeleteResponse) SetDpuBmcInterfaceDeleted(v bool) {
	o.DpuBmcInterfaceDeleted = v
}

// GetDpuMachineIds returns the DpuMachineIds field value
// If the value is explicit nil, the zero value for []string will be returned
func (o *MachineForceDeleteResponse) GetDpuMachineIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.DpuMachineIds
}

// GetDpuMachineIdsOk returns a tuple with the DpuMachineIds field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MachineForceDeleteResponse) GetDpuMachineIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.DpuMachineIds) {
		return nil, false
	}
	return o.DpuMachineIds, true
}

// SetDpuMachineIds sets field value
func (o *MachineForceDeleteResponse) SetDpuMachineIds(v []string) {
	o.DpuMachineIds = v
}

// GetDpuMachineInterfaceIds returns the DpuMachineInterfaceIds field value
// If the value is explicit nil, the zero value for []string will be returned
func (o *MachineForceDeleteResponse) GetDpuMachineInterfaceIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.DpuMachineInterfaceIds
}

// GetDpuMachineInterfaceIdsOk returns a tuple with the DpuMachineInterfaceIds field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MachineForceDeleteResponse) GetDpuMachineInterfaceIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.DpuMachineInterfaceIds) {
		return nil, false
	}
	return o.DpuMachineInterfaceIds, true
}

// SetDpuMachineInterfaceIds sets field value
func (o *MachineForceDeleteResponse) SetDpuMachineInterfaceIds(v []string) {
	o.DpuMachineInterfaceIds = v
}

func (o MachineForceDeleteResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MachineForceDeleteResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["allDone"] = o.AllDone
	toSerialize["managedHostMachineId"] = o.ManagedHostMachineId
	toSerialize["managedHostMachineInterfaceId"] = o.ManagedHostMachineInterfaceId
	toSerialize["instanceId"] = o.InstanceId
	toSerialize["managedHostBmcIp"] = o.ManagedHostBmcIp
	toSerialize["dpuBmcIp"] = o.DpuBmcIp
	toSerialize["ufmUnregistrations"] = o.UfmUnregistrations
	toSerialize["ufmUnregistrationPending"] = o.UfmUnregistrationPending
	toSerialize["initialLockdownState"] = o.InitialLockdownState
	toSerialize["machineUnlocked"] = o.MachineUnlocked
	toSerialize["hostInterfacesDeleted"] = o.HostInterfacesDeleted
	toSerialize["dpuInterfacesDeleted"] = o.DpuInterfacesDeleted
	toSerialize["hostBmcInterfaceAssociated"] = o.HostBmcInterfaceAssociated
	toSerialize["dpuBmcInterfaceAssociated"] = o.DpuBmcInterfaceAssociated
	toSerialize["hostBmcInterfaceDeleted"] = o.HostBmcInterfaceDeleted
	toSerialize["dpuBmcInterfaceDeleted"] = o.DpuBmcInterfaceDeleted
	if o.DpuMachineIds != nil {
		toSerialize["dpuMachineIds"] = o.DpuMachineIds
	}
	if o.DpuMachineInterfaceIds != nil {
		toSerialize["dpuMachineInterfaceIds"] = o.DpuMachineInterfaceIds
	}
	return toSerialize, nil
}

func (o *MachineForceDeleteResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"allDone",
		"managedHostMachineId",
		"managedHostMachineInterfaceId",
		"instanceId",
		"managedHostBmcIp",
		"dpuBmcIp",
		"ufmUnregistrations",
		"ufmUnregistrationPending",
		"initialLockdownState",
		"machineUnlocked",
		"hostInterfacesDeleted",
		"dpuInterfacesDeleted",
		"hostBmcInterfaceAssociated",
		"dpuBmcInterfaceAssociated",
		"hostBmcInterfaceDeleted",
		"dpuBmcInterfaceDeleted",
		"dpuMachineIds",
		"dpuMachineInterfaceIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMachineForceDeleteResponse := _MachineForceDeleteResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varMachineForceDeleteResponse)

	if err != nil {
		return err
	}

	*o = MachineForceDeleteResponse(varMachineForceDeleteResponse)

	return err
}

type NullableMachineForceDeleteResponse struct {
	value *MachineForceDeleteResponse
	isSet bool
}

func (v NullableMachineForceDeleteResponse) Get() *MachineForceDeleteResponse {
	return v.value
}

func (v *NullableMachineForceDeleteResponse) Set(val *MachineForceDeleteResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMachineForceDeleteResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMachineForceDeleteResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMachineForceDeleteResponse(val *MachineForceDeleteResponse) *NullableMachineForceDeleteResponse {
	return &NullableMachineForceDeleteResponse{value: val, isSet: true}
}

func (v NullableMachineForceDeleteResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMachineForceDeleteResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
